### ISSUE TITLE
Missing flag in documentation

### ISSUE THREAD

**Issue by therealmaxmoon** [DC23/scriptabit#27]
Text from the documentation:

Feed **any food** to quest pets only:
`sb-pets --feed-pets --no-base-pets --quest-pets`

But the flag _--any-pet-food_ is missing

Found here: https://scriptabit.readthedocs.io/en/latest/usage/petcare.html

**Comment by DC23** [comment]
Yep, that's a typo in the docs. I hope to release a new version today (adding some tag management functions for Lord Vlad). I will update the docs in that release.

**Comment by DC23** [comment]
Fixed in 1.17.0
